# Generated by Django 4.0.3 on 2023-03-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrecord",
            name="sales_price",
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
